# Generated by Django 5.1.6 on 2025-02-08 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('tipo_centro', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('horario', models.TextField(blank=True, null=True)),
                ('servicio_dialisis', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaDia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionPrevia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsejoNutricional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinutaNutricional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_vigencia', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('expirada', 'Expirada')], default='activa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('preparacion', models.TextField()),
                ('informacion_nutricional', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('energia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cenizas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hidratos_carbono', models.DecimalField(decimal_places=2, max_digits=5)),
                ('azucares_totales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fibra_dietetica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lipidos_totales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acidos_grasos_saturados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acidos_grasos_monoinsaturados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acidos_grasos_poliinsaturados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acidos_grasos_trans', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamina_A', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_C', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_D', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_E', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_K', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_B1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_B2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('niacina', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_B6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('acido_pantotenico', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamina_B12', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('folatos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potasio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calcio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fosforo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('magnesio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hierro', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cobre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('selenio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alcohol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriaalimento')),
            ],
        ),
        migrations.CreateModel(
            name='PorcionAlimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porciones', to='api.alimento')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenComida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(upload_to='imagenes/')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.receta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMinuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comidadia')),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.minutanutricional')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receta')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alimento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='api.receta')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('edad__gt', 0)), name='edad_gt_0'), models.CheckConstraint(condition=models.Q(('email__regex', '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')), name='email_valido')],
            },
        ),
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.alimento')),
                ('porcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.porcionalimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_comida', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='minutanutricional',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='AnalisisImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.JSONField()),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_imagenes', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condiciones_especificas', models.TextField(blank=True, null=True)),
                ('tipo_dialisis', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to='api.usuario')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('peso__gt', 0), ('peso__lt', 500)), name='peso_valido'), models.CheckConstraint(condition=models.Q(('altura__gt', 0), ('altura__lt', 3)), name='altura_valida')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCondicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.condicionprevia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='api.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'condicion')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
