# Generated by Django 5.1.6 on 2025-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='carbohidratos',
        ),
        migrations.AddField(
            model_name='alimento',
            name='humedad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
