# Generated by Django 5.1.6 on 2025-02-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_alimento_carbohidratos_alimento_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejonutricional',
            name='url_imagen',
            field=models.CharField(max_length=255),
        ),
    ]
