# Generated by Django 5.1.6 on 2025-03-06 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_consejonutricional_url_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('foto_perfil', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='respuestacomentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='analisisimagen',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='minutanutricional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilmedico',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='registrocomida',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilmedico',
            name='condiciones_especificas',
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='nivel_actividad',
            field=models.CharField(choices=[('sedentario', 'Sedentario'), ('ligera', 'Ligera'), ('moderada', 'Moderada'), ('alta', 'Alta'), ('muy alta', 'Muy Alta')], default='sedentario', max_length=50),
        ),
        migrations.AlterField(
            model_name='analisisimagen',
            name='url_imagen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagencomida',
            name='url_imagen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='minutanutricional',
            name='estado',
            field=models.CharField(default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariocondicion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocondicion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analisisimagen',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_imagenes', to='api.persona'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AddField(
            model_name='minutanutricional',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='api.persona'),
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='id_persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to='api.persona'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='api.persona'),
        ),
        migrations.AddField(
            model_name='registrocomida',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_comida', to='api.persona'),
        ),
        migrations.AddField(
            model_name='respuestacomentario',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AddField(
            model_name='usuariocondicion',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='api.persona'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.persona'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocondicion',
            unique_together={('id_persona', 'condicion')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('id_persona', 'rol')},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usuariocondicion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='usuario',
        ),
        migrations.CreateModel(
            name='VinculoPacienteCuidador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.persona')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to='api.persona')),
            ],
            options={
                'unique_together': {('paciente', 'cuidador')},
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
