# Generated by Django 5.1.6 on 2025-03-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_persona_remove_publicacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmedico',
            name='tipo_dialisis',
            field=models.CharField(choices=[('hemodialisis', 'Hemodiálisis'), ('dialisis_peritoneal', 'Diálisis Peritoneal')], default='hemodialisis', max_length=50),
        ),
    ]
