# Generated by Django 5.1.6 on 2025-03-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_perfilmedico_tipo_dialisis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
