# Generated by Django 5.1.6 on 2025-03-08 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_persona_apellidos_alter_persona_nombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculopacientecuidador',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
