# Generated by Django 5.1.6 on 2025-03-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vinculopacientecuidador_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='respuestacomentario',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Respuesta a Comentario', 'verbose_name_plural': 'Respuestas a Comentarios'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_comentario',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='respuestacomentario',
            old_name='fecha_respuesta',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='likes',
        ),
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='respuestacomentario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respuestacomentario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.persona'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='api.persona'),
        ),
        migrations.AlterField(
            model_name='respuestacomentario',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_comentario', to='api.persona'),
        ),
    ]
