# Generated by Django 5.1.6 on 2025-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comentario_options_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='equivalencia_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Equivalencia en gramos (g)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='equivalencia_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Equivalencia en mililitros (ml)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='es_volumen',
            field=models.BooleanField(default=True, help_text='Indica si es una medida de volumen (ml) o de masa (g)'),
        ),
    ]
