# Generated by Django 5.1.6 on 2025-03-21 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_unidadmedida_equivalencia_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocomida',
            name='porcion',
        ),
        migrations.AddField(
            model_name='registrocomida',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadmedida'),
        ),
    ]
