# Generated by Django 5.1.6 on 2025-03-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_registrocomida_porcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='informacion_nutricional',
            new_name='materiales',
        ),
        migrations.AddField(
            model_name='receta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='url_imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ImagenComida',
        ),
    ]
