# Generated by Django 5.1.6 on 2025-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_receta_bajo_en_fosforo_receta_bajo_en_potasio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tipo_receta',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('plato_principal', 'Plato Principal'), ('plato_fondo', 'Plato de Fondo'), ('postres_colaciones', 'Postres y Colaciones')], default='plato_principal', max_length=50),
        ),
    ]
