# Generated by Django 5.1.6 on 2025-05-12 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_centromedico_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionAlimentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleminuta',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='detalleminuta',
            name='minuta',
        ),
        migrations.RemoveField(
            model_name='detalleminuta',
            name='receta',
        ),
        migrations.AddField(
            model_name='detalleminuta',
            name='comida_dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.comidadia'),
        ),
        migrations.AddField(
            model_name='detalleminuta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleminuta',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detalleminuta',
            name='minuta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.minutanutricional'),
        ),
        migrations.AddField(
            model_name='detalleminuta',
            name='nombre_comida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NutrienteMinuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='MinutasRestricciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='api.minutanutricional')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutas_restricciones', to='api.restriccionalimentos')),
            ],
        ),
        migrations.CreateModel(
            name='RestriccionMinutaNutriente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nutriente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_nutrientes', to='api.nutrienteminuta')),
                ('restriccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_nutrientes', to='api.restriccionalimentos')),
            ],
        ),
    ]
