# Generated by Django 5.1.6 on 2025-05-14 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_foro_publicacion_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('notificaciones', models.BooleanField(default=True, help_text='Indica si el usuario recibirá notificaciones de este foro')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriptores', to='api.foro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foros_suscritos', to='api.persona')),
            ],
            options={
                'verbose_name': 'Suscripción a Foro',
                'verbose_name_plural': 'Suscripciones a Foros',
                'unique_together': {('foro', 'persona')},
            },
        ),
    ]
