# Generated by Django 5.1.6 on 2025-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_foropersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleminuta',
            name='comida_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleminuta',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nutrienteminuta',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
