# Generated by Django 5.1.6 on 2025-05-15 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_detalleminuta_comida_tipo_detalleminuta_dia_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleminuta',
            name='comida_dia',
        ),
        migrations.AlterField(
            model_name='detalleminuta',
            name='dia_semana',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleminuta',
            name='comida_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.comidatipo'),
        ),
        migrations.AddField(
            model_name='minutanutricional',
            name='minuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutas_nutricionales', to='api.minuta'),
        ),
        migrations.AlterField(
            model_name='detalleminuta',
            name='minuta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.minuta'),
        ),
        migrations.DeleteModel(
            name='ComidaDia',
        ),
    ]
