# Generated by Django 5.1.6 on 2025-05-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_comidatipo_minuta_remove_detalleminuta_comida_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='minuta',
            name='tipo_dialisis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalleminuta',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
