# Generated by Django 5.1.6 on 2025-05-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_minuta_genero_minuta_tipo_dialisis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='tipo_dialisis',
            field=models.CharField(blank=True, choices=[('hemodialisis', 'Hemodiálisis'), ('dialisis_peritoneal', 'Diálisis Peritoneal'), ('ambas', 'Ambas')], max_length=50, null=True),
        ),
    ]
