# Generated by Django 5.1.6 on 2025-05-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_minuta_tipo_dialisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='bajo_en_fosforo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minuta',
            name='bajo_en_potasio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minuta',
            name='bajo_en_proteinas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minuta',
            name='bajo_en_sodio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minuta',
            name='calorias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
