# Generated by Django 5.1.6 on 2025-05-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_minuta_bajo_en_fosforo_minuta_bajo_en_potasio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutanutricional',
            name='nombre_minuta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minutanutricional',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='minutanutricional',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='api.persona'),
        ),
        migrations.AlterField(
            model_name='minutanutricional',
            name='minuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='api.minuta'),
        ),
    ]
