# Generated by Django 5.1.6 on 2025-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_minutanutricional_nombre_minuta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisimagen',
            name='alimentos_detectados',
            field=models.ManyToManyField(blank=True, related_name='apariciones_en_analisis', to='api.alimento'),
        ),
        migrations.AddField(
            model_name='analisisimagen',
            name='compatible_con_perfil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analisisimagen',
            name='texto_original',
            field=models.TextField(blank=True, help_text='Descripción original generada por IA', null=True),
        ),
    ]
