# Generated by Django 5.1.6 on 2025-06-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_analisisimagen_alimentos_detectados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisisimagen',
            name='compatible_con_perfil',
        ),
        migrations.RemoveField(
            model_name='analisisimagen',
            name='texto_original',
        ),
    ]
