# Generated by Django 5.1.6 on 2025-06-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_analisisimagen_compatible_con_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisisimagen',
            old_name='conclusion',
            new_name='nombre',
        ),
    ]
