# Generated by Django 5.1.6 on 2025-06-08 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_conclusion_analisisimagen_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionesAnalisis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alimento_original', models.CharField(help_text='Nombre del alimento detectado originalmente', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('alimento_seleccionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_analisis', to='api.alimento')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='api.analisisimagen')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_analisis', to='api.persona')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_analisis', to='api.unidadmedida')),
            ],
            options={
                'verbose_name': 'Selección de Análisis',
                'verbose_name_plural': 'Selecciones de Análisis',
                'unique_together': {('analisis', 'alimento_original')},
            },
        ),
    ]
