# Generated by Django 5.1.6 on 2025-06-19 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_alimento_acido_pantotenico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisIngredientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(max_length=255)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.JSONField()),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ingredientes', to='api.persona')),
            ],
            options={
                'verbose_name': 'Análisis de Ingredientes',
                'verbose_name_plural': 'Análisis de Ingredientes',
            },
        ),
    ]
