# Generated by Django 5.1.6 on 2025-07-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_analisisingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
    ]
