# Generated by Django 5.1.6 on 2025-07-03 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocomida',
            name='fecha_consumo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
