# Generated by Django 5.1.6 on 2025-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_registrocomida_fecha_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centromedico',
            name='tipo_centro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
