# Generated by Django 5.1.6 on 2025-07-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_centromedico_tipo_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centromedico',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='tipo_centro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
