# Generated by Django 5.1.6 on 2025-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_centromedico_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centromedico',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='latitud',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='longitud',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='centromedico',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
